# Generated by Django 4.2.3 on 2023-07-19 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.UUID("5ac44659-d824-47a8-a413-15da766084ca"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("todo_title", models.CharField(max_length=255)),
                ("todo_description", models.TextField()),
                ("is_done", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
