# Generated by Django 4.2.3 on 2023-07-19 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("0f70d70d-2912-40e9-b966-3c09cc94373b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
