# Generated by Django 4.2.3 on 2023-07-19 10:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_todo_created_at_alter_todo_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("60311499-af35-415b-9307-1059cde64ffa"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="TimingsTodo",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.UUID("60311499-af35-415b-9307-1059cde64ffa"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timing", models.DateTimeField()),
                (
                    "todo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.todo"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
