# Generated by Django 4.2.3 on 2023-07-19 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0003_alter_todo_uid_timingstodo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="timingstodo",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("2a22d0a1-4864-474b-8cd5-f7d86cc6da4a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("2a22d0a1-4864-474b-8cd5-f7d86cc6da4a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
