# Generated by Django 4.2.3 on 2023-07-19 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_todo_user_alter_timingstodo_uid_alter_todo_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timingstodo",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
